language: node_js
node_js:
- '6'
script:
- sh scripts/coverage.sh
deploy:
  provider: npm
  email: ben@ajaxscape.com
  api_key:
    secure: dvIWlDIu1+Sqf66eW8S3Bu73pJy5/zD5Gu+dU/H8DAt11UvPGzTpUQ9f7zWidg8y1zPliGdaYvXAVwS2+AzxB/RuABbVXujno2Z9uWp5lqvFbJeHink1S+07YTNU3t7tDh7zMGePmouJb2nlQMwWc+BxCLvfZgI+YTccBBrPo6qHsFqEfS29+J8sOkbcyO9n2qRYedMb1WDO7xwkWTsoShwfrTNmAIuPUvgH79zSwU7EUJmiRN2IskH9Wg2+wh5qFMe2uNvKD4e9OSxiN3EZoNRned/RYw9oIbbnOR6m4+XqVmxha4jaDGlVzMQAbm8oZncLI70Rs+yzhhpw/8bbeFZXOkwWz6exnorGvFYWHT7rReb1oAnhRkkSkuN4ShsecFrFP3ZjhXe3pJoMzql/MPdoXMlSRo0ubiElzbO71nsHI8ZGoIK0iT+KpXLZpjptWutRsMwip2i2p68Zmni/GXYgL4gp5goSiGzvbXdPoFtY4zqPxi3uvQLXi9BPKZw0KyfQorztyFc2klol+95iWZq+KWlK4GuRGGmWnmp66d2uVO43p6jPKHeBK++P6chx6bDq6R9hogwhhB19hguOFXAjljuY9QecHqFSMALiL+tGPXpfRlQRl2A3G5FEEGNX5BygFl6IeW+dTX+r3MUqMLgcwEFn5DAj9pmdOhUVKx8=
  on:
    repo: ajaxscape/tamarin
