language: node_js
node_js:
- '6'
script:
- sh scripts/coverage.sh
deploy:
  provider: npm
  email: ben@ajaxscape.com
  api_key:
    secure: hZUB/yf7qvKrlMH/AbkcSA0cQb6bWz5LvLjLbzaiOGpzxTsLvL4RisFeGYZ/4KoKFtzE0xr5xMadqjOHNfUlnPkBdcLQq96A8hW7q4P2w7SDFimfNLp+JGQZkFehD18ubfiKyCN67fhop2vhgMmQls0ZPcSYdzdv8HunXKoVIe4U+0dhzRtODNheAXxsPixe1vxaxZDJoWXQA7KpSq7eJbYaJ2VZmAdghfwf/UKYk0IajGzu2TrDet196czcjR2sDV6v6fdPoUm/a9pPNQrH7O7qCEeZ9cuEmlns4kgV5GunCE4lk8SburJXCvQKrY0dMk/RJDpKqr+rsIQ3f65NwuLWZalM+Qzqxwkt+Z0j2lz5CVZw4RNL/4w3Rm217N/GUV7agUiuRnkC2X575q6IMO29yNyS7oxJ7bbgLHMjspUJpRG8AAtLdGJI/uWwzXnYkodVsUV/yf88w2b8zWhOFcSxTux4u46IAunkYoWEi9uWuRPPbZIlpnoOLYeyv7dpZZVXFOSs/2ajG5IIinbboa3FoQjzboJP04aEgBXxPCkVa8WB+rdDisQyHoDSPkrhu/d5a5Dce1AHueS0Ks6IOfAexSEBeM9PoSBiVAj2irzjUHeg6Q1sE9Cf9t/v2EXsavsu1DY7MsBpbY/ndZXNNY6xI5tTkkEXQk7+dDbD70k=
  on:
    repo: ajaxscape/tamarin
    branch: master
