language: node_js
node_js:
- '6'
script:
- sh scripts/coverage.sh
deploy:
  provider: npm
  email: ben@ajaxscape.com
  api_key:
    secure: GASaYcsCq/TRC4NMcdfMa9yG7OdBddk6bz+H4GvQPmqR62l/R79zGYl1jCBmllX7dRJDuaweoqy48noZy+bonm+CGaYCo8X/OHEDNc+/oIgmbqzEuTXwL0HqCZOnPl1r58kFhaIzbQOf/l1XX7Owm6dpQi28WesXSQECVZd0IuhPpgKtiSOLxq5FwleuVk7UA9QBVj5zPYiQKK5JWTxk2eIXXgNcWC8uwKuzsE5JqluBRkJ+HRGQ+2jp/C/HLlSfImVtqwM0jNqZ6KYigU0JQx0Hn8FqMSe5AVKNIEF9YJX51bkNTOc3AkZCgMM28sqNOS+t0xV5Vm9E2wTHGhpg6mZLJMY16EZI3t+6qBJnm0hZusZckcSS0qP7jbMCSE4//jsdxjAL3KcePuPmYH6tK3n5a2Q5zUGWG1jff/ATeoQ5I0uZtb11qVUehNjQF4fFmtVf68vLQ/4nX3sdNiRdncE3HeYy1iy7Ny2gxpnDR8jUcNm3usDeghHhPsTYRL0ig7cWNhqS3aS3mGAx7Har3d7NjyA4+eOmTLp1Sm048EvJ6OM0MCfU7i58LLnpJlpevCJbB7xwSvwIY8VvMa2h7dfal/mTc025XEwrSZSFswWlQx/BHKCjnS+gmE2IGCIo6PwJMGoqVbz1i9q8J9IJvnKRgFdVXqf6+3ks4UDMgoA=
  on:
    repo: ajaxscape/tamarin
    branch: master
