language: node_js
node_js:
- '6'
script:
- sh scripts/coverage.sh
deploy:
  provider: npm
  email: ben@ajaxscape.com
  api_key:
    secure: c02bR24ot3Jw+URItZdPraPk7V+9z9lDPlUu6rrkFePYUQ8iXy0rsWPDSUF7ChQT0FDcZTiJeMoMwT7ZLqEIeHLhNLitwpQkgGerPR4YOnS+dhyX4dvC8dbkI+WU2e/VkOek51OisWqs0cno12Sa0Wh4zpQl7CNhDBBFtN21jZoIqB3BsSZeVR+J6gO9oSHQ8Ji6EpYMnQV7PEcvBVBeb2m8U8YzI2UzKPrALwRwWmxNWNnva5L1onkG6q/y83J45ZzJxQnlXGZ0G2V3qnVoBEyHEmAlVGCkXqHBG8R9W0gcNz/ITZ7D0a3ebVFezzzCI3Xr4VtwgOc1HyyHbMr+/2t/vShPfxtE+74lN7/MfabOHwEThk6oVjrK5VpUOV/y0HN2102VLhJ+t7psLP5UfVjSy4MC84fs/gLIYyFQnIBHAs+3IzldQDS2GZXIxsW3WDX4ltjIsW9Yo2qsUAJ7ugE9c1oR4Xdiroo4CAA5eVpXsqjBqWc+uZZ/hJYNlZ+FGZXfjUQA2suwARUcxJceGTGOfKoJPmCoapVO/nh+DKbAHOuPTow5uCXQoyLuIigQDuB1sUmywAwQXDCR7QVLGqv4sD8ZvoWc3udqvbGxQpocEw/fovNM6dYHoOwCdISBEPDY859C6p5bkClS13I03VF225qbkbYtbKu6H2wK4+k=
  on:
    repo: ajaxscape/tamarin
